version: "3.9"
services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - ./.env.test
    depends_on:
      - postgres_test

  postgres_test:
    image: postgres:latest
    ports:
      - '6432:5432'
    env_file:
      - ./.env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
