
version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
