version: "3.9"
services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - ./.env.test
    depends_on:
      - postgres_test
      - redis_test

  postgres_test:
    image: postgres:latest
    ports:
      - '6432:5432'
    env_file:
      - ./.env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:latest
    ports:
      - '7379:6379'
    volumes:
      - redis_test_data:/data

volumes:
  postgres_test_data:
  redis_test_data:
