# Use the official Python base image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /test

# Install Python dependencies for testing and the application
COPY ./app /test/app
COPY ./tests /test/tests
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the FastAPI tests
CMD ["pytest"]
